// 10 cuentos largos (18 páginas de historia + portada + página final = 20 hojas).
// Cada página: text (español) e img (descripción de la escena en inglés para Higgsfield).
const C = {
  tobi: 'Tobi the chubby light brown bear cub with a cream tummy',
  lila: 'Lila the white bunny with long ears and pink inner ears',
  nico: 'Nico the white bunny with long ears and pink inner ears',
  pipo: 'Pipo the tiny round blue bird',
  tina: 'Tina the small green turtle with a darker green shell',
  buho: 'Grandma Owl, a plump brown owl with big round eyes',
  luz: 'Luz the little glowing yellow star with a cute face',
  pincho: 'Pincho the small round hedgehog with brown spikes and a cream face',
  bubu: 'Bubu the round orange fish with big eyes',
  dumbi: 'Dumbi the big blue-grey baby elephant with pink inner ears',
  ani: 'Ani the tiny brown ant with a happy face',
  fito: 'Fito the orange fox with a white chest and fluffy tail',
  misu: 'Misu the grey kitten with big eyes',
  nube: 'Nube the small fluffy white cloud with a cute face (a cloud only, no body, no legs)',
  mari: 'a small pink and yellow butterfly',
};
const S = {
  forest: 'in a sunny cartoon forest with round green trees and pines',
  meadow: 'in a green meadow with rolling hills, little flowers and a smiling sun',
  sunset: 'in a meadow under a warm orange and pink sunset sky',
  night: 'in a forest at night with a starry sky and a big soft full moon',
  cave: 'at the dark entrance of a little cave in the forest',
  river: 'beside a small sparkling river in the forest',
  garden: 'in a garden with a wooden fence, grass and a watering can',
  gardenbloom: 'in a garden bursting with colorful flowers and a wooden fence',
  sea: 'under the sea, blue water, sandy bottom, corals and seaweed',
  surface: 'at the sea surface, waves and a blue sky with a few clouds above',
  village: 'on a cozy village street with three pastel houses',
  bakery: 'in front of a small cute bakery with a striped awning and cakes in the window',
  sky: 'high in the blue sky among soft white clouds',
  rain: 'in a garden on a rainy day, grey sky, raindrops falling',
  picnic: 'in a meadow with a pink checkered picnic blanket and a basket',
  home: 'inside a cozy little cottage room with a round window and a soft bed',
};
const p = (text, img) => ({ text, img });

module.exports = [
  {
    id: '01', slug: 'tobi-el-osito-que-compartia', title: 'Tobi, el osito que compartía', hero: 'bear', heroDesc: C.tobi,
    lesson: 'Compartir hace que la alegría sea más grande.', question: '¿Qué te gustaría compartir hoy con alguien?', bg: 'forest',
    pages: [
      p('Tobi era un osito café que vivía en una casita de madera en medio del bosque.', `${C.tobi} smiling in front of a small wooden cottage ${S.forest}`),
      p('Lo que más le gustaba en el mundo era la miel. Dulce, dorada y pegajosa.', `${C.tobi} dreaming happily with hearts in his eyes, thinking about honey, ${S.forest}`),
      p('Cada mañana salía a pasear con su cesta, buscando flores y abejas.', `${C.tobi} walking with a small basket ${S.forest}, bees and flowers around`),
      p('Un día, detrás de un árbol muy viejo, encontró un tarro enorme y brillante.', `${C.tobi} peeking behind an old big tree and finding a giant jar of golden honey ${S.forest}`),
      p('"¡Miel! ¡Y es toda para mí!", gritó Tobi, saltando de alegría.', `${C.tobi} jumping with joy next to a giant jar of golden honey ${S.forest}`),
      p('Cargó el tarro hasta su casita. Pesaba mucho, pero no le importaba.', `${C.tobi} carrying a giant honey jar on his back, walking toward his cottage ${S.forest}`),
      p('Entonces escuchó unos pasitos. Era Lila, la coneja, con la pancita vacía.', `${C.tobi} holding a honey jar, ${C.lila} arriving looking sad and hungry ${S.forest}`),
      p('Y detrás llegó Pipo, el pajarito, con las alas caídas. "No encontramos nada de comer".', `${C.tobi}, ${C.lila} and ${C.pipo} with drooping wings, all together, ${S.forest}`),
      p('Tobi abrazó su tarro. "Si comparto, me quedará menos", pensó.', `${C.tobi} hugging a giant honey jar tightly with a worried face ${S.forest}`),
      p('Se sentó solo y comió una cucharada. Pero la miel no sabía tan rica como siempre.', `${C.tobi} sitting alone eating honey with a spoon, looking unhappy, ${S.forest}`),
      p('Miró por la ventana. Sus amigos estaban sentados, calladitos y tristes.', `${C.tobi} looking out a window of his cottage at ${C.lila} and ${C.pipo} sitting sadly outside ${S.forest}`),
      p('Tobi sintió un nudo en la pancita. Y no era hambre.', `${C.tobi} thinking with a sad face, holding a spoon, inside his cottage ${S.home}`),
      p('Abrió la puerta de golpe. "¡Vengan! ¡Hay miel para todos!"', `${C.tobi} opening his cottage door wide with a big happy smile, ${C.lila} and ${C.pipo} surprised outside ${S.forest}`),
      p('Lila dio un brinco enorme. Pipo revoloteó cantando de felicidad.', `${C.lila} jumping high and ${C.pipo} flying happily, ${C.tobi} laughing, ${S.forest}`),
      p('Se sentaron los tres en la hierba y comieron miel hasta llenarse.', `${C.tobi}, ${C.lila} and ${C.pipo} sitting on the grass sharing a big honey jar, ${S.meadow}`),
      p('Rieron, contaron cuentos y jugaron a atrapar mariposas toda la tarde.', `${C.tobi}, ${C.lila} and ${C.pipo} playing and chasing ${C.mari}, ${S.meadow}`),
      p('Al atardecer, Tobi probó otra cucharada. ¡Ahora sí sabía deliciosa!', `${C.tobi} tasting honey with a spoon and a delighted face, friends beside him, ${S.sunset}`),
      p('Y así aprendió que la miel, y todo lo bueno, sabe mejor cuando se comparte.', `${C.tobi}, ${C.lila} and ${C.pipo} hugging together happily ${S.sunset}`),
    ],
  },
  {
    id: '02', slug: 'tina-la-tortuga-paciente', title: 'Tina, la tortuga paciente', hero: 'turtle', heroDesc: C.tina,
    lesson: 'Las cosas buenas necesitan tiempo y cariño.', question: '¿Qué cosa estás esperando con paciencia?', bg: 'garden',
    pages: [
      p('Tina era una tortuga pequeña que caminaba despacito, muy despacito.', `${C.tina} walking slowly and smiling ${S.garden}`),
      p('Vivía en un jardín tranquilo, con una cerca de madera y mucha tierra suave.', `${C.tina} in a quiet garden with soft brown soil ${S.garden}`),
      p('Una mañana encontró algo chiquito y café en el suelo. ¡Era una semilla!', `${C.tina} looking surprised at a tiny brown seed on the soil ${S.garden}`),
      p('"¿Qué serás tú?", le preguntó Tina con curiosidad.', `${C.tina} looking closely at a tiny seed with curious eyes ${S.garden}`),
      p('Hizo un hoyito con su patita y puso la semilla adentro, con mucho cuidado.', `${C.tina} digging a small hole in the soil with her paw and placing a seed ${S.garden}`),
      p('La tapó con tierra y le dio un poquito de agua con su regadera azul.', `${C.tina} watering a small mound of soil with a blue watering can ${S.garden}`),
      p('Nico, el conejo, pasó corriendo. "¡Tina! ¡Ahí no hay nada! ¡Ven a jugar!"', `${C.tina} next to a mound of soil, ${C.nico} running past and laughing ${S.garden}`),
      p('"Ya habrá", dijo Tina sonriendo. Y siguió regando su semilla.', `${C.tina} smiling calmly and watering the soil while ${C.nico} looks puzzled ${S.garden}`),
      p('Pasó un día. Pasaron dos. Pasó una semana entera. Y no salía nada.', `${C.tina} sitting patiently next to bare soil, a calendar-like sun and moon in the sky, ${S.garden}`),
      p('Tina no se rindió. Cada mañana regaba la tierra y le cantaba una canción.', `${C.tina} singing with musical notes to a mound of soil, holding a watering can ${S.garden}`),
      p('Nico volvió a pasar. "¿Todavía sigues ahí? ¡Qué aburrido!"', `${C.nico} shrugging and laughing next to ${C.tina} who keeps watering ${S.garden}`),
      p('Una mañana, Tina vio algo verde y diminuto asomándose por la tierra.', `${C.tina} amazed looking at a tiny green sprout coming out of the soil ${S.garden}`),
      p('"¡Un brote!", gritó feliz. Y lo cuidó todavía con más cariño.', `${C.tina} cheering happily next to a small green sprout ${S.garden}`),
      p('El brote creció y creció. Le salieron hojas grandes y un tallo alto.', `${C.tina} looking up at a tall green plant with big leaves ${S.garden}`),
      p('Y un día apareció un botón amarillo que se abrió al sol.', `${C.tina} watching a big yellow sunflower bud opening toward the sun ${S.gardenbloom}`),
      p('¡Era un girasol gigante! Más alto que la cerca y más brillante que el sol.', `${C.tina} tiny next to a giant tall sunflower, taller than the wooden fence ${S.gardenbloom}`),
      p('Nico llegó y se quedó con la boca abierta. "¡Guau! ¿Cómo lo hiciste?"', `${C.nico} with mouth wide open in amazement looking at a giant sunflower, ${C.tina} smiling ${S.gardenbloom}`),
      p('Tina sonrió: "Con paciencia y cariño. Las cosas bonitas necesitan tiempo".', `${C.tina} and ${C.nico} sitting together under a giant sunflower ${S.sunset}`),
    ],
  },
  {
    id: '03', slug: 'nico-el-conejo-valiente', title: 'Nico, el conejo valiente', hero: 'rabbit', heroDesc: C.nico,
    lesson: 'Ser valiente es tener miedo y, aun así, ayudar.', question: '¿Qué haces tú cuando sientes miedo?', bg: 'night',
    pages: [
      p('Nico era un conejo blanco muy alegre. De día saltaba y jugaba sin parar.', `${C.nico} jumping happily ${S.meadow}`),
      p('Pero cuando el sol se escondía, Nico se escondía también.', `${C.nico} hiding under a blanket in his burrow while the sun sets outside the window ${S.home}`),
      p('La noche era oscura y llena de ruidos raros. A Nico le temblaban las orejas.', `${C.nico} scared with trembling ears looking out at the dark forest ${S.night}`),
      p('Una noche escuchó un llanto pequeñito. "¡Pío, pío!". Venía del bosque.', `${C.nico} at his burrow door listening, surprised, ${S.night}`),
      p('"Alguien necesita ayuda", pensó. Pero sus patitas no querían moverse.', `${C.nico} frozen with fear at the edge of the dark forest ${S.night}`),
      p('La abuela Búho lo vio desde su rama. "¿Qué pasa, pequeño?"', `${C.nico} looking up at ${C.buho} sitting on a tree branch ${S.night}`),
      p('"Tengo miedo de la oscuridad", dijo Nico con la voz chiquita.', `${C.nico} sad and small talking to ${C.buho} on a branch ${S.night}`),
      p('"Respira despacito", dijo la abuela. "Mira las estrellas. Escucha con el corazón".', `${C.buho} gently talking to ${C.nico}, both looking up at bright stars ${S.night}`),
      p('Nico respiró hondo. Uno, dos, tres. Y miró el cielo lleno de lucecitas.', `${C.nico} taking a deep breath with closed eyes under a sky full of stars ${S.night}`),
      p('Dio un paso. Luego otro. El bosque ya no parecía tan oscuro.', `${C.nico} walking carefully into the forest lit by moonlight ${S.night}`),
      p('Siguió el llanto hasta un arbusto. Ahí estaba Pipo, un pajarito perdido.', `${C.nico} finding ${C.pipo} crying under a bush ${S.night}`),
      p('"No tengas miedo", le dijo Nico. "Yo también lo tengo, pero estoy aquí".', `${C.nico} gently comforting ${C.pipo} ${S.night}`),
      p('Pipo se subió a su cabeza y juntos caminaron entre los árboles.', `${C.pipo} sitting on top of ${C.nico}'s head as they walk through the forest ${S.night}`),
      p('Cruzaron el río saltando piedras. Nico saltó primero para mostrar el camino.', `${C.nico} with ${C.pipo} on his head hopping across stones ${S.river} at night`),
      p('Por fin encontraron el nido de Pipo. Su mamá los esperaba con las alas abiertas.', `${C.nico} delivering ${C.pipo} to a nest where a mother blue bird waits with open wings ${S.night}`),
      p('"¡Gracias, Nico!", cantaron los pajaritos. Nico se sintió grande como un oso.', `${C.nico} proud and happy with blue birds singing around him ${S.night}`),
      p('De regreso, la abuela Búho le guiñó un ojo. "Eso, pequeño, es ser valiente".', `${C.buho} winking at ${C.nico} who smiles proudly ${S.night}`),
      p('Desde esa noche, Nico ya no se esconde. Sabe que el miedo se hace pequeño cuando ayudas.', `${C.nico} standing brave and happy under the moon with ${C.pipo} and ${C.buho} ${S.night}`),
    ],
  },
  {
    id: '04', slug: 'la-estrellita-que-perdio-su-brillo', title: 'La estrellita que perdió su brillo', hero: 'star', heroDesc: C.luz,
    lesson: 'La amabilidad hace brillar a los demás.', question: '¿A quién puedes ayudar a brillar con una palabra amable?', bg: 'night',
    pages: [
      p('En lo alto del cielo vivía Luz, una estrellita pequeña pero muy brillante.', `${C.luz} shining brightly in the night sky above the forest ${S.night}`),
      p('Cada noche iluminaba el bosque para que los animalitos encontraran su camino.', `${C.luz} in the sky lighting a path in the forest where small animals walk ${S.night}`),
      p('Pero una noche, Luz se sintió muy sola. Las otras estrellas estaban muy lejos.', `${C.luz} looking sad and alone in a wide dark sky with tiny distant stars ${S.night}`),
      p('Su brillo empezó a apagarse, poquito a poco, como una vela.', `${C.luz} dim and sad, her glow fading ${S.night}`),
      p('Y sin luz para sostenerse, cayó suavemente hasta el bosque. ¡Plof!', `${C.luz} falling gently from the sky into the forest, leaving a soft trail ${S.night}`),
      p('Pincho, el erizo, salía de su cueva cuando vio algo amarillo en la hierba.', `${C.pincho} coming out of ${S.cave} and spotting ${C.luz} lying on the grass`),
      p('"¿Estás bien?", preguntó. "No brillo", dijo Luz con una lágrima.', `${C.pincho} looking worried at ${C.luz} who has a tear on her cheek ${S.night}`),
      p('Pincho no sabía qué hacer. Así que fue a buscar a la abuela Búho.', `${C.pincho} running through the forest to find ${C.buho} on her branch ${S.night}`),
      p('La abuela Búho llegó volando. Miró a Luz con sus grandes ojos y sonrió.', `${C.buho} flying down next to ${C.luz} and ${C.pincho} ${S.night}`),
      p('"Las estrellas brillan con cariño", dijo. "Vamos a hacerle compañía".', `${C.buho}, ${C.pincho} and ${C.luz} sitting together in a circle on the grass ${S.night}`),
      p('Pincho le contó un cuento gracioso. Luz sonrió un poquito.', `${C.pincho} telling a funny story with his paws up, ${C.luz} smiling slightly ${S.night}`),
      p('La abuela Búho le cantó una canción suave. Un chispita amarilla apareció.', `${C.buho} singing with musical notes, ${C.luz} with a tiny spark of light ${S.night}`),
      p('Llegaron Nico y Tobi con flores. "Eres muy especial, Luz", le dijeron.', `${C.nico} and ${C.tobi} bringing flowers to ${C.luz}, ${C.pincho} and ${C.buho} beside ${S.night}`),
      p('Y con cada palabra amable, Luz brillaba un poquito más.', `${C.luz} glowing brighter surrounded by ${C.pincho}, ${C.buho}, ${C.nico} and ${C.tobi} ${S.night}`),
      p('Hasta que brilló tanto que iluminó todo el bosque como si fuera de día.', `${C.luz} shining extremely bright lighting the whole forest, friends shielding their eyes happily ${S.night}`),
      p('"¡Ya puedo volver!", dijo Luz. Y se despidió con un abrazo de cada amigo.', `${C.luz} hugging ${C.pincho} goodbye, other friends waving ${S.night}`),
      p('Subió al cielo despacito, dejando un caminito de chispas doradas.', `${C.luz} rising into the sky leaving a trail of golden sparkles, friends watching from below ${S.night}`),
      p('Desde entonces, cada noche, Luz guiña un ojo a sus amigos. Y ellos le mandan un beso.', `${C.luz} winking from the sky, ${C.pincho}, ${C.buho}, ${C.nico} and ${C.tobi} blowing kisses from the ground ${S.night}`),
    ],
  },
  {
    id: '05', slug: 'bubu-el-pez-que-queria-volar', title: 'Bubu, el pez que quería volar', hero: 'fish', heroDesc: C.bubu,
    lesson: 'Cada uno tiene algo especial que lo hace único.', question: '¿Qué cosa haces tú muy bien?', bg: 'sea',
    pages: [
      p('Bubu era un pececito naranja que vivía en un mar azul y tranquilo.', `${C.bubu} swimming happily ${S.sea}`),
      p('Tenía una cueva de coral, amigos caracoles y burbujas para jugar.', `${C.bubu} playing with bubbles near a coral cave and little snails ${S.sea}`),
      p('Pero cada tarde subía a la superficie y miraba el cielo con ojos soñadores.', `${C.bubu} poking his head out of the water looking up at the sky dreamily ${S.surface}`),
      p('Allá arriba pasaba Pipo, el pajarito azul, volando libre entre las nubes.', `${C.bubu} in the water watching ${C.pipo} flying high among the clouds ${S.surface}`),
      p('"¡Yo quiero volar como él!", suspiraba Bubu.', `${C.bubu} sighing with a dreamy sad face at the surface, ${C.pipo} in the sky ${S.surface}`),
      p('Así que tomó impulso y saltó con todas sus fuerzas. ¡Plaf! Cayó al agua.', `${C.bubu} leaping out of the water with a big splash ${S.surface}`),
      p('Saltó otra vez. Y otra. Y otra más. Siempre volvía a caer.', `${C.bubu} mid-air after a jump, splashes around, looking frustrated ${S.surface}`),
      p('Cansado y triste, se hundió hasta el fondo y se escondió en su cueva.', `${C.bubu} sad hiding inside a coral cave ${S.sea}`),
      p('Pipo lo había visto todo. Bajó hasta la orilla y lo llamó.', `${C.pipo} standing on the sandy shore calling toward the water ${S.surface}`),
      p('"¿Por qué estás triste?", preguntó. "Porque no puedo volar", dijo Bubu.', `${C.bubu} at the surface talking with ${C.pipo} on the shore ${S.surface}`),
      p('Pipo se rió con cariño. "¿Y sabes qué? Yo no puedo nadar".', `${C.pipo} laughing kindly next to the water, ${C.bubu} surprised ${S.surface}`),
      p('"No conozco los corales de colores, ni las burbujas, ni las cuevas del mar".', `${C.pipo} peeking curiously into the water where colorful corals glow ${S.surface}`),
      p('Bubu se quedó pensando. Luego dijo: "¡Ven! ¡Te enseño mi mundo!"', `${C.bubu} smiling excitedly inviting ${C.pipo} to look into the water ${S.surface}`),
      p('Nadó rapidísimo entre las algas, dio vueltas y saltó por encima de una ola.', `${C.bubu} swimming fast doing loops among seaweed ${S.sea}`),
      p('Pipo aplaudía con las alas. "¡Eres el mejor nadador que he visto!"', `${C.pipo} clapping his wings on the shore while ${C.bubu} shows off a jump ${S.surface}`),
      p('Bubu miró a su alrededor: corales, estrellas de mar, burbujas que bailaban. ¡Su mar era hermoso!', `${C.bubu} looking around amazed at colorful corals, starfish and dancing bubbles ${S.sea}`),
      p('Desde ese día, Pipo vuela por arriba y Bubu nada por abajo. Y juegan a las carreras.', `${C.pipo} flying above the waves and ${C.bubu} swimming just below racing together ${S.surface}`),
      p('Bubu ya no quiere volar. Aprendió que cada uno es especial a su manera.', `${C.bubu} happy and proud with ${C.pipo} beside him at the surface ${S.sunset}`),
    ],
  },
  {
    id: '06', slug: 'dumbi-y-la-hormiga-ani', title: 'Dumbi y la hormiga Ani', hero: 'elephant', heroDesc: C.dumbi,
    lesson: 'No importa el tamaño: todos podemos ayudar.', question: '¿En qué puedes ayudar tú, aunque seas pequeño?', bg: 'meadow',
    pages: [
      p('Dumbi era un elefante enorme. Sus pisadas hacían temblar las flores.', `${C.dumbi} walking heavily, flowers trembling ${S.meadow}`),
      p('Ani era una hormiga chiquitita. Cabía en la punta de una hoja.', `${C.ani} standing on the tip of a green leaf, very tiny, ${S.meadow}`),
      p('Los dos vivían en la misma pradera, pero Dumbi casi nunca la veía.', `${C.dumbi} looking around distractedly while ${C.ani} waves from the grass below ${S.meadow}`),
      p('"Eres tan pequeña, Ani", decía Dumbi riendo. "No puedes hacer nada importante".', `${C.dumbi} laughing and pointing his trunk at ${C.ani} who looks sad ${S.meadow}`),
      p('Ani agachaba las antenas y se iba callada a su hormiguero.', `${C.ani} walking away sadly toward a small anthill ${S.meadow}`),
      p('Dumbi tenía un tesoro: un cacahuate dorado que guardaba para su cumpleaños.', `${C.dumbi} proudly holding a shiny golden peanut with his trunk ${S.meadow}`),
      p('Un día, jugando cerca de las rocas, el cacahuate se le resbaló de la trompa.', `${C.dumbi} surprised as a golden peanut slips from his trunk near big grey rocks ${S.meadow}`),
      p('Rodó, rodó... y cayó dentro de una grieta muy angosta y muy profunda.', `a golden peanut falling into a narrow deep crack between rocks, ${C.dumbi} watching in shock ${S.meadow}`),
      p('Dumbi metió la trompa. ¡No cabía! Metió la pata. ¡Menos!', `${C.dumbi} trying to push his trunk into a narrow crack in the rocks, straining ${S.meadow}`),
      p('Empujó la roca con todas sus fuerzas. La roca no se movió ni un poquito.', `${C.dumbi} pushing a huge rock with all his strength, face red with effort ${S.meadow}`),
      p('Se sentó y una lágrima grande rodó por su mejilla. "Mi cacahuate…"', `${C.dumbi} sitting sadly with a big tear next to the rocks ${S.meadow}`),
      p('Ani escuchó el llanto desde su hormiguero y corrió a ver qué pasaba.', `${C.ani} running fast through the grass toward the rocks ${S.meadow}`),
      p('"Yo puedo entrar", dijo Ani. Dumbi la miró sin creerlo.', `${C.ani} standing bravely in front of the crack, ${C.dumbi} looking down doubtful ${S.meadow}`),
      p('Ani se metió por la grieta, bajó y bajó hasta encontrar el cacahuate.', `${C.ani} inside a dark narrow crack reaching a golden peanut ${S.meadow}`),
      p('Lo cargó sobre su espalda. Pesaba mucho, pero las hormigas son muy fuertes.', `${C.ani} carrying a golden peanut on her back, climbing up the crack ${S.meadow}`),
      p('Y salió con el cacahuate brillando al sol. "¡Aquí está!"', `${C.ani} emerging from the crack holding up the golden peanut, ${C.dumbi} amazed and happy ${S.meadow}`),
      p('"¡Gracias, Ani! Perdón por reírme de ti. Eres pequeña, pero muy valiente".', `${C.dumbi} kneeling down gently to ${C.ani}, both smiling warmly ${S.meadow}`),
      p('Desde entonces son los mejores amigos. Y comparten el cacahuate en cada cumpleaños.', `${C.dumbi} and ${C.ani} celebrating together with a golden peanut and a little party hat ${S.sunset}`),
    ],
  },
  {
    id: '07', slug: 'fito-el-zorro-y-las-palabras-magicas', title: 'Fito, el zorro y las palabras mágicas', hero: 'fox', heroDesc: C.fito,
    lesson: 'Las palabras amables abren todas las puertas.', question: '¿Cuáles son tus palabras mágicas?', bg: 'village',
    pages: [
      p('Fito era un zorro muy listo que vivía en un pueblito de casas de colores.', `${C.fito} standing proudly ${S.village}`),
      p('Sabía trepar, correr y contar hasta cien. Pero había algo que no sabía: pedir bien las cosas.', `${C.fito} climbing a fence and showing off ${S.village}`),
      p('"¡Dame eso!", le gritó a Misu, la gatita, y le quitó su pelota.', `${C.fito} snatching a red ball from ${C.misu} who looks sad ${S.village}`),
      p('"¡Quítate!", le dijo a Tina, la tortuga, y pasó empujándola.', `${C.fito} pushing past ${C.tina} rudely ${S.village}`),
      p('Poco a poco, nadie quería jugar con Fito. Se quedó solo en la plaza.', `${C.fito} sitting alone on a bench in an empty village square ${S.village}`),
      p('Un día olió algo delicioso: pastel de fresa recién hecho en la panadería.', `${C.fito} sniffing the air with delight in front of ${S.bakery}`),
      p('Entró y gritó: "¡Dame un pastel!". El oso panadero ni siquiera volteó.', `${C.fito} shouting at the counter while ${C.tobi} wearing a baker apron ignores him ${S.bakery}`),
      p('Gritó más fuerte. Pataleó. Nada. Fito salió sin pastel y con mucho enojo.', `${C.fito} stomping angrily out of the bakery empty-handed ${S.bakery}`),
      p('La abuela Búho lo vio sentado en la banqueta. "¿Qué te pasa, Fito?"', `${C.buho} perched on a lamp post looking at ${C.fito} sitting sadly on the curb ${S.village}`),
      p('"Nadie me da nada", dijo Fito. "Ni un pastel, ni una pelota, ni un amigo".', `${C.fito} complaining with crossed arms to ${C.buho} ${S.village}`),
      p('"Conozco dos palabras mágicas", dijo la abuela. "Abren puertas y corazones".', `${C.buho} whispering wisely to a curious ${C.fito} ${S.village}`),
      p('"Se dicen por favor… y gracias". Fito arrugó la nariz. "¿Eso es todo?"', `${C.fito} wrinkling his nose doubtfully while ${C.buho} nods ${S.village}`),
      p('Regresó a la panadería. Respiró hondo. "¿Me das un pastel, por favor?"', `${C.fito} at the bakery counter asking politely with a shy smile, ${C.tobi} as the baker listening ${S.bakery}`),
      p('El oso panadero sonrió de oreja a oreja. Y le dio el pastel más grande de todos.', `${C.tobi} in a baker apron smiling widely handing a huge strawberry cake to ${C.fito} ${S.bakery}`),
      p('"¡Gracias!", dijo Fito. Y sintió un calorcito bonito en el pecho.', `${C.fito} holding a big strawberry cake with a warm happy face ${S.bakery}`),
      p('Fue con Misu: "¿Juegas conmigo, por favor?". Misu sonrió y le pasó la pelota.', `${C.fito} asking politely, ${C.misu} smiling and passing him a red ball ${S.village}`),
      p('Fue con Tina: "Perdón por empujarte". Tina lo invitó a comer pastel.', `${C.fito} apologizing to ${C.tina}, ${C.misu} beside, sharing a cake on a bench ${S.village}`),
      p('Desde ese día, Fito usa sus palabras mágicas siempre. Y la plaza está llena de amigos.', `${C.fito}, ${C.misu}, ${C.tina} and ${C.tobi} playing together happily in the village square ${S.sunset}`),
    ],
  },
  {
    id: '08', slug: 'nube-la-nubecita-grunona', title: 'Nube, la nubecita gruñona', hero: 'cloud', heroDesc: C.nube,
    lesson: 'Está bien sentir tristeza, y todos tenemos un lugar importante.', question: '¿Qué te hace sentir mejor cuando estás triste?', bg: 'sky',
    pages: [
      p('Nube era una nubecita blanca y esponjosa que vivía en lo alto del cielo.', `${C.nube} floating ${S.sky}`),
      p('Casi siempre estaba contenta, flotando de aquí para allá con el viento.', `${C.nube} smiling and floating with a gentle breeze ${S.sky}`),
      p('Pero ese día amaneció gris, pesada y gruñona. No sabía por qué.', `${C.nube} looking grey, heavy and grumpy with a frown ${S.sky}`),
      p('Abajo, en la pradera, Misu y Tobi preparaban un picnic con pastelitos.', `${C.misu} and ${C.tobi} setting up cupcakes on a picnic blanket, ${C.nube} small and grey in the sky above ${S.picnic}`),
      p('"¡Qué día tan bonito!", dijo Misu. Nube los miró y se sintió todavía peor.', `${C.nube} grey and sad looking down at ${C.misu} and ${C.tobi} laughing on the picnic blanket ${S.picnic}`),
      p('Sentía algo apretado adentro, como si tuviera que llorar y no pudiera.', `${C.nube} very dark grey with a trembling lip, holding back tears ${S.sky}`),
      p('Y de pronto ya no aguantó más. ¡Plic, plac, plic! Empezó a llover.', `${C.nube} crying raindrops that fall onto the meadow below ${S.rain}`),
      p('Los pastelitos se mojaron. Misu y Tobi corrieron a esconderse bajo un paraguas rojo.', `${C.misu} and ${C.tobi} running under a red umbrella, wet cupcakes on the blanket, ${C.nube} raining above ${S.rain}`),
      p('"¡Ay, no!", pensó Nube. "Arruiné su día". Y lloró todavía más.', `${C.nube} crying harder with big raindrops ${S.rain}`),
      p('Lloró toda la tarde hasta que no le quedó ni una gotita.', `${C.nube} small, tired and light after raining, a few last drops falling ${S.rain}`),
      p('Se sintió vacía y ligera. Pero también un poco mejor.', `${C.nube} white again, calm, with a soft relieved expression ${S.sky} at dusk`),
      p('"Soy la peor nube del mundo", susurró, y se escondió detrás de la montaña.', `${C.nube} hiding shyly behind a mountain top ${S.sunset}`),
      p('A la mañana siguiente, escuchó una voz: "¡Nube! ¡Nube! ¡Baja a ver!"', `${C.misu} on a hill calling up to ${C.nube} who peeks from behind the mountain, morning light ${S.meadow}`),
      p('Era Misu. Y a su lado, el jardín estaba lleno de flores nuevas de todos los colores.', `${C.misu} showing a garden full of fresh colorful flowers, ${C.nube} watching from above ${S.gardenbloom}`),
      p('"Gracias a tu lluvia crecieron", dijo Misu. "¡Y mira, hasta llegaron mariposas!"', `${C.misu} pointing at ${C.mari} and flowers, ${C.nube} surprised and touched ${S.gardenbloom}`),
      p('Tobi trajo pastelitos nuevos. "Todos tenemos días grises", le dijo. "Está bien llorar".', `${C.tobi} holding a tray of cupcakes smiling up at ${C.nube} ${S.gardenbloom}`),
      p('Nube sonrió, y con su sonrisa apareció un arcoíris sobre el jardín.', `${C.nube} smiling with a bright rainbow appearing behind her over the garden ${S.gardenbloom}`),
      p('Aprendió que sentirse triste está bien, y que hasta la lluvia hace cosas bonitas.', `${C.nube} happy under a rainbow with ${C.misu}, ${C.tobi} and ${C.mari} below ${S.gardenbloom}`),
    ],
  },
  {
    id: '09', slug: 'misu-y-el-jardin', title: 'Misu y el jardín', hero: 'cat', heroDesc: C.misu,
    lesson: 'Cuidar la naturaleza nos regala belleza y vida.', question: '¿Cómo puedes cuidar las plantas y animales cerca de tu casa?', bg: 'garden',
    pages: [
      p('Misu era una gatita gris muy curiosa. Le gustaba explorar todos los rincones.', `${C.misu} exploring curiously ${S.village}`),
      p('Un día siguió a una mariposa y llegó a un lugar que no conocía.', `${C.misu} following ${C.mari} toward an old gate ${S.garden}`),
      p('Era un jardín. Pero un jardín triste: sin flores, con basura y tierra seca.', `${C.misu} looking sadly at a neglected garden full of litter, dry soil and no flowers ${S.garden}`),
      p('Había papeles, botellas y una lata vieja. La mariposa se fue volando.', `${C.misu} among scattered papers, plastic bottles and an old can, ${C.mari} flying away ${S.garden}`),
      p('"Pobre jardín", dijo Misu. "Nadie te cuida".', `${C.misu} touching the dry soil gently with a sad face ${S.garden}`),
      p('Y sin pensarlo dos veces, empezó a recoger la basura con sus patitas.', `${C.misu} picking up litter and putting it in a bag ${S.garden}`),
      p('Llenó una bolsa. Luego otra. ¡Era mucho trabajo para una gatita!', `${C.misu} tired next to two full garbage bags, wiping her forehead ${S.garden}`),
      p('Tina y Nico pasaron por ahí. "¿Qué haces, Misu?" "Cuido el jardín. ¿Me ayudan?"', `${C.tina} and ${C.nico} arriving while ${C.misu} holds a garbage bag ${S.garden}`),
      p('Entre los tres dejaron el jardín limpio. La tierra por fin podía respirar.', `${C.misu}, ${C.tina} and ${C.nico} standing proudly in a clean garden with bare soil ${S.garden}`),
      p('Nico trajo semillas de su casa. Tina trajo su regadera azul.', `${C.nico} holding a small bag of seeds and ${C.tina} carrying a blue watering can ${S.garden}`),
      p('Plantaron las semillas en hileras y les pusieron agua fresca.', `${C.misu}, ${C.tina} and ${C.nico} planting seeds in neat rows ${S.garden}`),
      p('Cada tarde Misu volvía. Regaba las plantitas y les hablaba bajito.', `${C.misu} alone watering small sprouts with a blue watering can at sunset ${S.garden}`),
      p('"Crezcan fuertes, amigas", les decía. Y los brotes parecían escucharla.', `${C.misu} whispering to little green sprouts that lean toward her ${S.garden}`),
      p('Aparecieron hojas. Luego botones. Y una mañana… ¡flores por todos lados!', `${C.misu} amazed as the garden fills with blooming colorful flowers ${S.gardenbloom}`),
      p('Rojas, amarillas, rosas y moradas. El jardín parecía un arcoíris.', `${C.misu} sitting in the middle of a garden full of red, yellow, pink and purple flowers ${S.gardenbloom}`),
      p('Y entonces volvió la mariposa. Y trajo a sus amigas. Y llegaron pajaritos a cantar.', `${C.misu} surrounded by many butterflies and ${C.pipo} singing on the fence ${S.gardenbloom}`),
      p('Misu invitó a todo el pueblo. "Este jardín es de todos. ¡Cuidémoslo juntos!"', `${C.misu}, ${C.tina}, ${C.nico}, ${C.tobi} and ${C.fito} celebrating in the flower garden ${S.gardenbloom}`),
      p('Misu aprendió que cuando cuidamos la naturaleza, ella nos regala belleza y vida.', `${C.misu} happy with ${C.mari} on her nose in the blooming garden ${S.sunset}`),
    ],
  },
  {
    id: '10', slug: 'pincho-el-erizo-que-queria-un-abrazo', title: 'Pincho, el erizo que quería un abrazo', hero: 'hedgehog', heroDesc: C.pincho,
    lesson: 'Ser diferente no impide tener amigos; con cariño todo se puede.', question: '¿Cómo le demuestras cariño a tus amigos?', bg: 'meadow',
    pages: [
      p('Pincho era un erizo pequeño con muchas, muchas púas en la espalda.', `${C.pincho} smiling ${S.meadow}`),
      p('Le encantaba jugar a las escondidas, cantar y rodar por las colinas.', `${C.pincho} rolling down a green hill happily ${S.meadow}`),
      p('Pero había algo que Pincho quería más que nada en el mundo: un abrazo.', `${C.pincho} looking wistfully at a heart-shaped cloud in the sky ${S.meadow}`),
      p('Cuando intentó abrazar a Nico, el conejo saltó hacia atrás. "¡Ay! ¡Pinchas!"', `${C.pincho} reaching out to hug, ${C.nico} jumping back startled ${S.meadow}`),
      p('Cuando intentó abrazar a Misu, la gatita se escondió detrás de un árbol.', `${C.pincho} with open arms, ${C.misu} hiding behind a tree ${S.forest}`),
      p('Hasta la abuela Búho, que quería a todos, dijo: "Mejor desde lejos, pequeño".', `${C.buho} on a branch politely keeping distance from ${C.pincho} below ${S.forest}`),
      p('Pincho se fue a sentar solo bajo un árbol grande.', `${C.pincho} sitting alone under a big tree ${S.forest}`),
      p('"Nadie me abrazará nunca", pensó. Y una lágrima rodó por su nariz.', `${C.pincho} crying softly under a tree with a tear on his nose ${S.forest}`),
      p('Tobi, el oso, lo vio desde lejos. No le gustaba ver triste a un amigo.', `${C.tobi} watching ${C.pincho} sadly from a distance ${S.forest}`),
      p('Se sentó a su lado, sin tocarlo, y le preguntó qué le pasaba.', `${C.tobi} sitting next to ${C.pincho} under the tree, listening ${S.forest}`),
      p('"Quiero un abrazo", dijo Pincho. "Pero mis púas lastiman a todos".', `${C.pincho} explaining sadly, pointing at his spikes, ${C.tobi} thinking ${S.forest}`),
      p('Tobi se rascó la cabeza. Pensó y pensó. Y de pronto, ¡tuvo una idea!', `${C.tobi} with a lightbulb idea expression next to ${C.pincho} ${S.forest}`),
      p('Corrió a su casa y volvió con una manta rosa, suave y calientita.', `${C.tobi} running back carrying a soft pink blanket ${S.forest}`),
      p('La puso con cuidado sobre las púas de Pincho, como una capa.', `${C.tobi} placing a pink blanket over ${C.pincho}'s spikes like a cape ${S.forest}`),
      p('"¡Ahora sí!", dijo Tobi. Y le dio un abrazo grande, grande.', `${C.tobi} hugging ${C.pincho} wrapped in a pink blanket, both very happy ${S.forest}`),
      p('Pincho cerró los ojos. Era el abrazo más calientito del mundo.', `${C.pincho} with eyes closed and a blissful smile inside ${C.tobi}'s hug ${S.forest}`),
      p('Nico y Misu llegaron corriendo. "¡Nosotros también!". Y fue un abrazo de cuatro.', `${C.tobi}, ${C.nico} and ${C.misu} all hugging ${C.pincho} wrapped in a pink blanket ${S.forest}`),
      p('Pincho aprendió que ser diferente no es malo. Con amigos que te quieren, siempre hay una solución.', `${C.pincho} with the pink blanket cape walking happily with ${C.tobi}, ${C.nico} and ${C.misu} ${S.sunset}`),
    ],
  },
];
