// 10 cuentos cortos con enseñanza. Cada página: escena + texto.
module.exports = [
  {
    id: '01', slug: 'tobi-el-osito-que-compartia', title: 'Tobi, el osito que compartía', hero: 'bear',
    lesson: 'Compartir hace que la alegría sea más grande.',
    question: '¿Qué te gustaría compartir hoy con alguien?',
    pages: [
      { text: 'Tobi era un osito que vivía en el bosque. Lo que más le gustaba en el mundo era la miel.', sc: { bg: 'forest', chars: [{ t: 'bear', x: 500, mood: 'happy' }] } },
      { text: 'Una mañana encontró un tarro de miel enorme y dorado. "¡Qué rico!", dijo con los ojos muy abiertos.', sc: { bg: 'forest', chars: [{ t: 'bear', x: 420, mood: 'surprised' }], front: [{ t: 'honey', x: 600, y: 560, s: 1.3 }] } },
      { text: 'Entonces llegaron sus amigos: Lila la coneja y Pipo el pajarito. Tenían mucha hambre.', sc: { bg: 'forest', chars: [{ t: 'bear', x: 300, mood: 'happy' }, { t: 'rabbit', x: 620, mood: 'sad', flip: true }, { t: 'bird', x: 820, y: 560, mood: 'sad', flip: true }], front: [{ t: 'honey', x: 460, y: 560 }] } },
      { text: 'Tobi pensó: "Si comparto, me quedará menos miel para mí…". Y se quedó muy callado.', sc: { bg: 'forest', chars: [{ t: 'bear', x: 500, mood: 'sad' }], front: [{ t: 'honey', x: 500, y: 560, s: 0.9 }] } },
      { text: 'Pero vio las caritas tristes de sus amigos y sonrió. "¡Vengan! ¡Hay miel para todos!"', sc: { bg: 'forest', chars: [{ t: 'bear', x: 280, mood: 'big' }, { t: 'rabbit', x: 640, mood: 'happy', flip: true }, { t: 'bird', x: 830, y: 560, mood: 'happy', flip: true }], front: [{ t: 'honey', x: 470, y: 560, s: 1.1 }] } },
      { text: 'Comieron juntos y rieron toda la tarde. Tobi descubrió que la miel sabe mucho mejor con amigos.', sc: { bg: 'sunset', chars: [{ t: 'bear', x: 300, mood: 'happy' }, { t: 'rabbit', x: 560, mood: 'happy' }, { t: 'bird', x: 760, y: 560, mood: 'happy', flip: true }], front: [{ t: 'honey', x: 880, y: 560, s: 0.8 }] } },
    ],
  },
  {
    id: '02', slug: 'tina-la-tortuga-paciente', title: 'Tina, la tortuga paciente', hero: 'turtle',
    lesson: 'Las cosas buenas necesitan tiempo y cariño.',
    question: '¿Qué cosa estás esperando con paciencia?',
    pages: [
      { text: 'Tina era una tortuga tranquila. Un día encontró una semilla pequeñita en el jardín.', sc: { bg: 'garden', chars: [{ t: 'turtle', x: 420, mood: 'surprised' }], front: [{ t: 'seed', x: 640, y: 560, s: 1.5 }] } },
      { text: 'La plantó con cuidado en la tierra y le puso un poquito de agua.', sc: { bg: 'garden', chars: [{ t: 'turtle', x: 380, mood: 'happy' }], front: [{ t: 'wateringcan', x: 620, y: 560 }] } },
      { text: 'Su amigo Nico el conejo pasó corriendo. "¡Ahí no hay nada, Tina! ¡Vamos a jugar!"', sc: { bg: 'garden', chars: [{ t: 'turtle', x: 350, mood: 'happy' }, { t: 'rabbit', x: 720, mood: 'surprised', flip: true }] } },
      { text: 'Pero Tina volvía cada día. Regaba su semilla y le cantaba una cancioncita.', sc: { bg: 'garden', chars: [{ t: 'turtle', x: 400, mood: 'sleepy' }], front: [{ t: 'sprout', x: 640, y: 560, s: 1.2 }, { t: 'wateringcan', x: 200, y: 560, s: 0.7 }] } },
      { text: 'Pasaron muchos días. Y una mañana… ¡un girasol gigante y amarillo miraba al sol!', sc: { bg: 'gardenbloom', chars: [{ t: 'turtle', x: 380, mood: 'big' }], front: [{ t: 'sunflower', x: 660, y: 560, s: 1.6 }] } },
      { text: 'Nico se quedó con la boca abierta. Tina sonrió: "Las cosas bonitas necesitan tiempo y cariño".', sc: { bg: 'gardenbloom', chars: [{ t: 'turtle', x: 330, mood: 'happy' }, { t: 'rabbit', x: 560, mood: 'surprised' }], front: [{ t: 'sunflower', x: 800, y: 560, s: 1.6 }] } },
    ],
  },
  {
    id: '03', slug: 'nico-el-conejo-valiente', title: 'Nico, el conejo valiente', hero: 'rabbit',
    lesson: 'Ser valiente es tener miedo y, aun así, ayudar.',
    question: '¿Qué haces tú cuando sientes miedo?',
    pages: [
      { text: 'Nico era un conejo muy alegre de día. Pero cuando llegaba la noche, sentía mucho miedo.', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 500, mood: 'sad' }] } },
      { text: 'Una noche escuchó un ruido: "¡Pío, pío!". Alguien estaba llorando en la oscuridad.', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 380, mood: 'surprised' }, { t: 'bird', x: 760, y: 560, s: 0.8, mood: 'sad', flip: true }] } },
      { text: 'La abuela Búho le dijo: "Respira despacito, mira las estrellas y escucha con el corazón".', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 360, mood: 'sad' }, { t: 'owl', x: 700, y: 560, mood: 'happy', flip: true }] } },
      { text: 'Nico respiró hondo. Sus patitas temblaban, pero dio un paso… y luego otro.', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 500, mood: 'surprised' }] } },
      { text: 'Encontró a un pajarito perdido. "No tengas miedo, yo te llevo a casa", le dijo Nico.', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 420, mood: 'happy' }, { t: 'bird', x: 640, y: 560, s: 0.8, mood: 'happy', flip: true }] } },
      { text: 'Esa noche Nico entendió algo: ser valiente no es no tener miedo, sino ayudar aunque lo sientas.', sc: { bg: 'night', chars: [{ t: 'rabbit', x: 340, mood: 'big' }, { t: 'bird', x: 560, y: 560, s: 0.8, mood: 'happy' }, { t: 'owl', x: 780, y: 560, mood: 'happy', flip: true }] } },
    ],
  },
  {
    id: '04', slug: 'la-estrellita-que-perdio-su-brillo', title: 'La estrellita que perdió su brillo', hero: 'star',
    lesson: 'La amabilidad hace brillar a los demás.',
    question: '¿A quién puedes ayudar a brillar con una palabra amable?',
    pages: [
      { text: 'En el cielo vivía Luz, una estrellita muy brillante que iluminaba el bosque cada noche.', sc: { bg: 'night', chars: [{ t: 'star', x: 500, y: 330, s: 0.9, mood: 'happy' }] } },
      { text: 'Pero una noche se sintió sola y triste. Su brillo se apagó y cayó suavemente al bosque.', sc: { bg: 'night', chars: [{ t: 'star', x: 500, mood: 'sad', s: 0.9 }] } },
      { text: 'Pincho el erizo la encontró. "¿Estás bien?", preguntó. "No brillo", dijo Luz llorando.', sc: { bg: 'night', chars: [{ t: 'star', x: 340, mood: 'sad', s: 0.85 }, { t: 'hedgehog', x: 720, mood: 'surprised', flip: true }] } },
      { text: 'Pincho llamó a la abuela Búho. Se sentaron junto a Luz y le contaron cuentos bonitos.', sc: { bg: 'night', chars: [{ t: 'star', x: 300, mood: 'sad', s: 0.85 }, { t: 'hedgehog', x: 560, mood: 'happy', flip: true }, { t: 'owl', x: 800, mood: 'happy', flip: true }] } },
      { text: '"Eres muy especial", le dijeron. Y poco a poco, Luz empezó a brillar otra vez.', sc: { bg: 'night', chars: [{ t: 'star', x: 340, mood: 'happy', s: 0.9 }, { t: 'hedgehog', x: 600, mood: 'big', flip: true }, { t: 'owl', x: 830, mood: 'happy', flip: true }], props: [{ t: 'heart', x: 460, y: 380, s: 0.8 }] } },
      { text: 'Luz volvió al cielo más brillante que nunca. Desde entonces, cada noche guiña un ojo a sus amigos.', sc: { bg: 'night', chars: [{ t: 'star', x: 500, y: 320, s: 0.9, mood: 'big' }, { t: 'hedgehog', x: 320, mood: 'happy' }, { t: 'owl', x: 720, mood: 'happy', flip: true }] } },
    ],
  },
  {
    id: '05', slug: 'bubu-el-pez-que-queria-volar', title: 'Bubu, el pez que quería volar', hero: 'fish',
    lesson: 'Cada uno tiene algo especial que lo hace único.',
    question: '¿Qué cosa haces tú muy bien?',
    pages: [
      { text: 'Bubu era un pececito naranja que vivía en el mar azul. Le encantaba mirar el cielo.', sc: { bg: 'sea', chars: [{ t: 'fish', x: 500, y: 520, mood: 'happy' }] } },
      { text: 'Cada día veía pasar a Pipo el pájaro. "¡Yo quiero volar como él!", suspiraba Bubu.', sc: { bg: 'sea', chars: [{ t: 'fish', x: 400, y: 520, mood: 'sad' }, { t: 'bird', x: 700, y: 230, mood: 'happy', flip: true }] } },
      { text: 'Bubu saltó y saltó, pero siempre caía al agua. ¡Plaf! Se sintió muy triste.', sc: { bg: 'sea', chars: [{ t: 'fish', x: 500, y: 300, mood: 'surprised', flip: true }] } },
      { text: 'Pipo bajó a la orilla. "Yo no puedo nadar ni ver los peces de colores. ¡Tú sí!", le dijo.', sc: { bg: 'sea', chars: [{ t: 'fish', x: 380, y: 520, mood: 'surprised' }, { t: 'bird', x: 640, y: 640, mood: 'happy', flip: true }] } },
      { text: 'Bubu miró a su alrededor: corales, burbujas, algas que bailaban. ¡Su mar era hermoso!', sc: { bg: 'sea', chars: [{ t: 'fish', x: 500, y: 520, mood: 'big' }, { t: 'butterfly', x: 250, y: 470, s: 0.6 }] } },
      { text: 'Desde ese día, Pipo vuela por arriba y Bubu nada por abajo. Cada uno es especial a su manera.', sc: { bg: 'sea', chars: [{ t: 'fish', x: 420, y: 520, mood: 'happy' }, { t: 'bird', x: 600, y: 240, mood: 'happy' }] } },
    ],
  },
  {
    id: '06', slug: 'dumbi-y-la-hormiga-ani', title: 'Dumbi y la hormiga Ani', hero: 'elephant',
    lesson: 'No importa el tamaño: todos podemos ayudar.',
    question: '¿En qué puedes ayudar tú, aunque seas pequeño?',
    pages: [
      { text: 'Dumbi era un elefante enorme. Ani era una hormiga chiquitita. Vivían en la misma pradera.', sc: { bg: 'meadow', chars: [{ t: 'elephant', x: 360, mood: 'happy' }, { t: 'ant', x: 760, mood: 'happy', s: 1.4, flip: true }] } },
      { text: '"Eres muy pequeña, Ani. No puedes hacer nada importante", decía Dumbi riéndose.', sc: { bg: 'meadow', chars: [{ t: 'elephant', x: 360, mood: 'big' }, { t: 'ant', x: 760, mood: 'sad', s: 1.4, flip: true }] } },
      { text: 'Un día, a Dumbi se le cayó su cacahuate favorito dentro de una grieta muy angosta.', sc: { bg: 'meadow', chars: [{ t: 'elephant', x: 340, mood: 'surprised' }], front: [{ t: 'rock', x: 720, y: 560, s: 1.2 }, { t: 'crack', x: 720, y: 560 }, { t: 'peanut', x: 720, y: 545, s: 0.6 }] } },
      { text: 'Su trompa era demasiado grande. Intentó y intentó, pero no lo alcanzaba. ¡Qué tristeza!', sc: { bg: 'meadow', chars: [{ t: 'elephant', x: 420, mood: 'sad' }], front: [{ t: 'rock', x: 760, y: 560, s: 1.2 }, { t: 'crack', x: 760, y: 560 }] } },
      { text: 'Ani se acercó: "Yo puedo entrar". Se metió en la grieta y salió cargando el cacahuate.', sc: { bg: 'meadow', chars: [{ t: 'elephant', x: 340, mood: 'surprised' }, { t: 'ant', x: 700, mood: 'big', s: 1.4, flip: true }], front: [{ t: 'rock', x: 820, y: 560 }, { t: 'peanut', x: 640, y: 505, s: 0.8 }] } },
      { text: '"¡Gracias, Ani! Perdón por reírme de ti", dijo Dumbi. Desde entonces son los mejores amigos.', sc: { bg: 'sunset', chars: [{ t: 'elephant', x: 380, mood: 'happy' }, { t: 'ant', x: 740, mood: 'happy', s: 1.4, flip: true }], props: [{ t: 'heart', x: 560, y: 360, s: 0.7 }] } },
    ],
  },
  {
    id: '07', slug: 'fito-el-zorro-y-las-palabras-magicas', title: 'Fito, el zorro y las palabras mágicas', hero: 'fox',
    lesson: 'Las palabras amables abren todas las puertas.',
    question: '¿Cuáles son tus palabras mágicas?',
    pages: [
      { text: 'Fito era un zorro listo, pero muy mandón. "¡Dame eso!", "¡Quítate!", gritaba a todos.', sc: { bg: 'village', chars: [{ t: 'fox', x: 400, mood: 'big' }, { t: 'cat', x: 720, mood: 'sad', flip: true }] } },
      { text: 'Un día quiso un pastel de la panadería. "¡Dame un pastel!", gritó. Nadie le hizo caso.', sc: { bg: 'village', chars: [{ t: 'fox', x: 380, mood: 'sad' }, { t: 'bear', x: 720, mood: 'sad', flip: true }], front: [{ t: 'cake', x: 560, y: 560 }] } },
      { text: 'La abuela Búho lo vio triste. "Fito, existen dos palabras mágicas: por favor y gracias".', sc: { bg: 'village', chars: [{ t: 'fox', x: 380, mood: 'surprised' }, { t: 'owl', x: 700, mood: 'happy', flip: true }] } },
      { text: 'Fito regresó a la panadería. "¿Me das un pastel, por favor?", dijo con voz suave.', sc: { bg: 'village', chars: [{ t: 'fox', x: 380, mood: 'happy' }, { t: 'bear', x: 720, mood: 'surprised', flip: true }], front: [{ t: 'cake', x: 560, y: 560 }] } },
      { text: '¡Y funcionó! El oso panadero sonrió y le dio el pastel más grande. "¡Gracias!", dijo Fito.', sc: { bg: 'village', chars: [{ t: 'fox', x: 380, mood: 'big' }, { t: 'bear', x: 720, mood: 'happy', flip: true }], front: [{ t: 'cake', x: 560, y: 560, s: 1.3 }] } },
      { text: 'Desde ese día, Fito usa sus palabras mágicas todos los días. Y tiene muchos más amigos.', sc: { bg: 'village', chars: [{ t: 'fox', x: 300, mood: 'happy' }, { t: 'cat', x: 540, mood: 'happy' }, { t: 'bear', x: 800, mood: 'happy', flip: true }] } },
    ],
  },
  {
    id: '08', slug: 'nube-la-nubecita-grunona', title: 'Nube, la nubecita gruñona', hero: 'cloud',
    lesson: 'Está bien sentir tristeza, y todos tenemos un lugar importante.',
    question: '¿Qué te hace sentir mejor cuando estás triste?',
    pages: [
      { text: 'Nube era una nubecita que vivía en el cielo. Ese día se sentía gruñona y muy gris.', sc: { bg: 'sky', chars: [{ t: 'cloud', x: 500, y: 400, mood: 'sad' }] } },
      { text: 'Abajo, Misu la gata y Tobi el oso hacían un picnic. "¡Qué día tan bonito!", decían.', sc: { bg: 'picnic', chars: [{ t: 'cloud', x: 500, y: 250, s: 0.7, mood: 'sad' }, { t: 'cat', x: 320, mood: 'happy' }, { t: 'bear', x: 700, mood: 'happy', flip: true }], front: [{ t: 'basket', x: 510, y: 590, s: 0.8 }] } },
      { text: 'Nube no aguantó más y se puso a llorar. ¡Plic, plac! Empezó a llover sobre el picnic.', sc: { bg: 'rain', chars: [{ t: 'cloud', x: 500, y: 250, s: 0.7, mood: 'sad' }, { t: 'cat', x: 320, mood: 'surprised' }, { t: 'bear', x: 700, mood: 'surprised', flip: true }], front: [{ t: 'umbrella', x: 520, y: 560, s: 0.9 }] } },
      { text: '"Perdón, arruiné su día", dijo Nube muy apenada. Se sentía la peor nube del mundo.', sc: { bg: 'rain', chars: [{ t: 'cloud', x: 500, y: 330, s: 0.9, mood: 'sad' }] } },
      { text: 'Pero al día siguiente, Misu la llamó: "¡Mira! Gracias a tu lluvia, el jardín se llenó de flores".', sc: { bg: 'gardenbloom', chars: [{ t: 'cloud', x: 500, y: 250, s: 0.7, mood: 'surprised' }, { t: 'cat', x: 380, mood: 'big' }, { t: 'butterfly', x: 700, y: 420, s: 0.7 }] } },
      { text: 'Nube sonrió con arcoíris. Entendió que llorar está bien, y que su lluvia también hace cosas bonitas.', sc: { bg: 'gardenbloom', chars: [{ t: 'cloud', x: 500, y: 250, s: 0.7, mood: 'big' }, { t: 'cat', x: 320, mood: 'happy' }, { t: 'bear', x: 720, mood: 'happy', flip: true }] } },
    ],
  },
  {
    id: '09', slug: 'misu-y-el-jardin', title: 'Misu y el jardín', hero: 'cat',
    lesson: 'Cuidar la naturaleza nos regala belleza y vida.',
    question: '¿Cómo puedes cuidar las plantas y animales cerca de tu casa?',
    pages: [
      { text: 'Misu era una gatita curiosa. Un día encontró un jardín triste, lleno de basura y sin flores.', sc: { bg: 'garden', chars: [{ t: 'cat', x: 380, mood: 'sad' }], front: [{ t: 'trash', x: 660, y: 560 }, { t: 'trash', x: 820, y: 560, s: 0.7 }] } },
      { text: '"¡Pobre jardín!", dijo. Y sin pensarlo dos veces, empezó a recoger toda la basura.', sc: { bg: 'garden', chars: [{ t: 'cat', x: 400, mood: 'surprised' }], front: [{ t: 'trash', x: 600, y: 560, s: 0.8 }] } },
      { text: 'Sus amigos Tina y Nico llegaron a ayudar. Juntos plantaron semillas en la tierra limpia.', sc: { bg: 'garden', chars: [{ t: 'cat', x: 260, mood: 'happy' }, { t: 'turtle', x: 560, mood: 'happy' }, { t: 'rabbit', x: 820, mood: 'happy', flip: true }], front: [{ t: 'seed', x: 420, y: 560 }, { t: 'seed', x: 700, y: 560 }] } },
      { text: 'Cada tarde Misu regaba las plantitas y les hablaba bajito: "Crezcan fuertes, amigas".', sc: { bg: 'garden', chars: [{ t: 'cat', x: 380, mood: 'happy' }], front: [{ t: 'wateringcan', x: 560, y: 560, s: 0.9 }, { t: 'sprout', x: 700, y: 560 }, { t: 'sprout', x: 820, y: 560, s: 0.8 }] } },
      { text: 'Poco a poco el jardín se llenó de colores. ¡Y llegaron mariposas y pajaritos a visitarlo!', sc: { bg: 'gardenbloom', chars: [{ t: 'cat', x: 380, mood: 'big' }, { t: 'butterfly', x: 640, y: 400, s: 0.7 }, { t: 'bird', x: 820, y: 560, s: 0.8, mood: 'happy', flip: true }] } },
      { text: 'Misu aprendió que cuando cuidamos la naturaleza, la naturaleza nos regala belleza y vida.', sc: { bg: 'gardenbloom', chars: [{ t: 'cat', x: 300, mood: 'happy' }, { t: 'turtle', x: 560, mood: 'happy' }, { t: 'rabbit', x: 820, mood: 'happy', flip: true }, { t: 'butterfly', x: 700, y: 380, s: 0.6 }] } },
    ],
  },
  {
    id: '10', slug: 'pincho-el-erizo-que-queria-un-abrazo', title: 'Pincho, el erizo que quería un abrazo', hero: 'hedgehog',
    lesson: 'Ser diferente no impide tener amigos; con cariño todo se puede.',
    question: '¿Cómo le demuestras cariño a tus amigos?',
    pages: [
      { text: 'Pincho era un erizo pequeño con muchas púas. Le encantaba jugar con sus amigos.', sc: { bg: 'meadow', chars: [{ t: 'hedgehog', x: 500, mood: 'happy' }] } },
      { text: 'Pero cuando quería abrazar a alguien… "¡Ay, pinchas!", decían todos, y se alejaban.', sc: { bg: 'meadow', chars: [{ t: 'hedgehog', x: 380, mood: 'sad' }, { t: 'rabbit', x: 740, mood: 'surprised', flip: true }] } },
      { text: 'Pincho se sentó solo bajo un árbol. "Nadie me abrazará nunca", pensó con una lágrima.', sc: { bg: 'forest', chars: [{ t: 'hedgehog', x: 500, mood: 'sad' }] } },
      { text: 'Tobi el oso tuvo una idea. Trajo una manta muy suave y la puso sobre las púas de Pincho.', sc: { bg: 'forest', chars: [{ t: 'hedgehog', x: 380, mood: 'surprised' }, { t: 'bear', x: 720, mood: 'happy', flip: true }], front: [{ t: 'blanket', x: 380, y: 560, s: 0.9 }] } },
      { text: '"¡Ahora sí!", gritaron todos. Y le dieron el abrazo más grande y calientito del bosque.', sc: { bg: 'forest', chars: [{ t: 'bear', x: 280, mood: 'big' }, { t: 'hedgehog', x: 500, mood: 'big' }, { t: 'rabbit', x: 720, mood: 'happy', flip: true }], props: [{ t: 'heart', x: 500, y: 340, s: 0.9 }], front: [{ t: 'blanket', x: 500, y: 560, s: 0.9 }] } },
      { text: 'Pincho aprendió que ser diferente no es malo. Con amigos que te quieren, siempre hay una solución.', sc: { bg: 'sunset', chars: [{ t: 'bear', x: 280, mood: 'happy' }, { t: 'hedgehog', x: 520, mood: 'happy' }, { t: 'rabbit', x: 760, mood: 'happy', flip: true }, { t: 'butterfly', x: 640, y: 380, s: 0.6 }] } },
    ],
  },
];
